apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: std-dive-logger-dev
resources:
  - ../base
patches:
  - target: { kind: HTTPRoute, name: std-dive-logger-web }
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: std-dive-logger-web-dev.sthomas.ch
