name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FRONTEND_DIR: ./vue
  LINT_ENABLED: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Test and Lint
        uses: ./.github/actions/test-and-lint
        with:
          frontend-dir: ${{ env.FRONTEND_DIR }}
          lint-enabled: ${{ env.LINT_ENABLED }}
      
      - name: Build project
        working-directory: ${{ env.FRONTEND_DIR }}
        run: yarn build --mode staging
